### ISSUE TITLE
模板的附录部分需要更新

### ISSUE THREAD

**Issue by seisman** [ywgATustcbbs/ustcthesis#11]
模板的附录部分似乎与[中国科学技术大学研究生学位论文撰写规范](http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/1.doc)的规定不相符。

最明显的一点是，模板里的规范在页边距上左右不相等，而学校官方网站的规范里要求左右边距相等。

学校官方网站的模板是2007年发布的，不知道模板里的附录是什么时候的？学校网站提供的应该是最新的版本吧？

**Comment by ywgATustcbbs** [comment]
如果是指最后的排版，经过测量没有发现附录左右页边距有明显差距，如果你那里有这个问题，希望能有个再现的例子。

如果仅仅是说附录里的文字与学校规定有差异，这个在很久之前就知道与学校的存在一定的差异，所以在附录开头添加了说明：”附录的仅供参考，一切以学校规定为准“。之所以没有改，是因为太懒，记不得是从哪里直接复制来简单改了下格式，不想一句一句校对了……

**Comment by ywgATustcbbs** [comment]
如果是指最后的排版，经过测量没有发现附录左右页边距有明显差距，如果你那里有这个问题，希望能有个再现的例子。

如果仅仅是说附录里的文字与学校规定有差异，这个在很久之前就知道与学校的存在一定的差异，所以在附录开头添加了说明：”附录的仅供参考，一切以学校规定为准“。之所以没有改，是因为太懒，记不得是从哪里直接复制来简单改了下格式，不想一句一句校对了……

**Comment by seisman** [comment]
不是指排版，排版中左右边距是相等的，但是附录中的规范给出的左右边距是不等的。所以仅仅只是附录中的文字与学校规定有差异。

这个还是更新一下比较好。不过学校的论文撰写规范好像规定了好多内容，都贴进去好像也不太合适。

**Comment by ywgATustcbbs** [comment]
东西是挺多的，而且有很多表格之类的，加上有的地方是手工排版的……直接复制粘贴肯定不行，但是一点一点排版又不值当……毕竟模板只是展示下附录的效果，不是专门弄这个的……等下我来重新弄一下吧。

**Comment by seisman** [comment]
至少应该保证模板的附录是对的，然后再给一个官方规范的链接。

**Comment by ywgATustcbbs** [comment]
已更新，谢谢建议，如果你有空的话，可以帮助完善这些内容

**Comment by seisman** [comment]
恩，先提Issue，有时间再弄。
