### ISSUE TITLE
页码居中？

### ISSUE THREAD

**Issue by seisman** [ywgATustcbbs/ustcthesis#12]
关于页码位置，《规范》中有两种互相矛盾的说法。

在2.6.2.3节

```
页码从绪论开始按阿拉伯数字（1，2，3……）连续编排，此前的部分(中英文摘要、目录等)用大写罗马数    
字（I，II,III…）单独编排，页码位置居于页脚居中。封面、扉页、创新性声明等不编页码。
```

在3.1节

```
 页码 宋体10.5磅页面下脚右端
```

囧rz...

目前模板中页码位于页脚的单侧，《规范》的示例中页码位于中间。

**Comment by ywgATustcbbs** [comment]
关于页码位置，学校的说法矛盾是一方面，另一方面是学校的规定与“奇偶页不同”这一行业标准冲突，全部居右明显是单面打印的方式。全部居中的话不知道是出于什么考虑，或许是考虑到许多同学可能不太会用word做奇偶页不同的页码吧。

本着排版美观的原则，模板里是遵循行规，并没有按照学校规定来。其实最开始的模板是奇偶页的页边距也不同的，后来迁就学校规定了。

其实学校规定不合行规的地方多了，页眉、页边距等细节问题，从奇数页开始也没有说，倒是制本厂装订的时候会提醒学生每章从奇数页开始

**Comment by seisman** [comment]
关于页码是居中还是奇偶页不同，我看了一下我手边的文献，是两种情况都有的，所以这个是不是行业标准还不确定。

经常看到各大高校的LaTeX模板在吐槽学校的规范，但规范毕竟是规范，既然是作为模板，还是应该尽量严格按照规范来比较好。不然使用这个模板的人，还需要自己修改模板来达到学校的要求，这就失去了模板的意义了。

**Comment by ywgATustcbbs** [comment]
关于页码位置，大部分书籍都是在页面外侧。确实是行业惯例。以下是从stackexchange上复制来的
In the absence of a particular style guide, I would put the page numbers on the top of the page, toward the outer side. When printing single-sided, this means put them in the top right corner. When printing double-sided, this means put them in the top right corner on odd numbered pages, and top left corner on even numbered pages.

Putting the page number at the top puts it in a spot where people will quite naturally look.
Putting the page number on the outside makes it easy to quickly flip to a specific page.

学校的规定本身就是用word写的，制定规定的人并不一定对出版行业的惯例熟悉（当然我也是一知半解），甚至可以猜测制定规定的人连word都不一定用的很熟练。

我翻了身边的十几本教材，没有发现有页码居中布置的。作为双面打印的论文，一两百页也有一定的厚度，看做一本薄书也不为过，放在页面外侧是很合理的做法。

**Comment by seisman** [comment]
但是既然学校写了这样的规范，如果模板不按照规范来，那模板还有什么存在的价值呢？

等到毕业生都已经用模板写完了论文，才发现模板不符号要求，那不就坑了？

**Comment by ywgATustcbbs** [comment]
你说的有道理。但是总觉得难以忍受学校这种排版的做法。之后对这部分进行一些改动。

还是需要解释一下：之前一直没有按照学校的走，根据以前的情况看，学校对页码位置并没有很严格的要求，倒是之前到制本厂去看过，只对空白页要求必须适当插入。

在我个人看来，页码并不是一个严重的问题，甚至不能称之为问题，只是规范与惯例的取舍。我的理解中，愿意使用TeX的同学应该是对排版质量有一定要求的，或者说希望自己的论文更加美观的。如果页码居中放置，这种排版方式很明显是简单的用word随便添加一个页脚造成的结果，对论文整体排版来说无疑是一个污点。放在我身上，我之前在写本科论文的时候是绝对无法接受的，今后也不会在我的论文上妥协。

**Comment by ywgATustcbbs** [comment]
另外，贴一些排版相关的资料吧，如果有人有兴趣可以去看一下

这个维基在页面最下边可以展开，里边有很多关于排版的条目可以参考。
http://en.wikipedia.org/wiki/Typography

这是一个系列（看了这个系列很可能就会觉得word弱爆了）：
http://theworldsgreatestbook.com/book-design-part-1/

**Comment by seisman** [comment]
我的感觉是，现在的模板用户里有一些是完全没接触过LaTeX的。。。虽然我不理解他们为什么会选择在毕业论文里开始用LaTeX，对于这些人我也不觉得他们会在乎页码居中丑不丑。。

或者给模板再加个选项，修改选项来调用不同的页码风格，这样总比让用户修改模板要好一些。

**Comment by ywgATustcbbs** [comment]
是的，我现就是想这么办。包括页眉双线也这样提供选项。其他的小地方可能也比较多，一时想不起来了
