### ISSUE TITLE
引用格式及参考文献格式

### ISSUE THREAD

**Issue by seisman** [ywgATustcbbs/ustcthesis#13]
模板中目前引用采用编号，《规范》中推荐的写法是

```
在正文引用文献处标注著者姓名与出版年份，在文后的参考文献表中标注参考文献的详细信息。
```

也可采用顺序编码方式：

```
参考文献如果按照顺序编码制著录，可参照GB/T 7714-2005《文后参考文献著录规则》执行。
```

**Comment by ywgATustcbbs** [comment]
这个参考文献格式是多年的老毛病了，因为对bibtex没有深入研究过，所以一直没有动

**Comment by wzhd** [comment]
之前我是这样使用了biblatex的，使用了biber后端，开启了natbib格式支持

> \usepackage[backend=biber,sorting=none,natbib=true]{biblatex}

支持 `\cite` 和这些格式

|  |  |
| --- | --- |
| \citep | (Jones, 1958) |
| \citet | Jones (1958) |
| \citealt | Jones 1958 |

添加bib文件路径

> \addbibresource{文件绝对路径.文件扩展名}

列出参考文献

> \printbibliography

**Comment by ywgATustcbbs** [comment]
非常感谢建议，等以后有空再弄吧，希望有人能够帮忙弄一下
