### ISSUE TITLE
Key Words or Keywords

### ISSUE THREAD

**Issue by seisman** [ywgATustcbbs/ustcthesis#17]
我查了一下不同的期刊，有的用`key words`有的用`keywords`，似乎没有一个统一的标准，姑且认为两个都是对的。

学校的规范中使用的是`Key Words`， 模板里是否改成跟规范一致？

**Comment by ywgATustcbbs** [comment]
keywords应该是正确的拼写
http://en.wikipedia.org/wiki/Keywords

**Comment by seisman** [comment]
但是在这个词条下在解释`Corpus linguistic keywords`的时候多次用到了`key words`
