### ISSUE TITLE
将notchinese放在单独的文件中

### ISSUE THREAD

**Issue by seisman** [ywgATustcbbs/ustcthesis#22]
建议将notchinese相关的语句放在单独的文件中，主要原因是notchinese选项在实际中很少会被用到。而现在代码的处理中，有多处对notchinese进行判断，如果为真则执行非中文的设置，如果为假则执行中文的设置。这样使得代码看上去比较乱。

我的建议是，把notchinese相关的选项都放在notchinese.cls中。ustcthesis.cls中只包含中文相关的设置，然后在结尾处判断notchinese，若为真则把notchinese.cls包含进来，notchinese.cls中的选项覆盖中文的相关设置。

**Comment by ywgATustcbbs** [comment]
当时的想法是在主文件中实现所有基本的设置，这样即使少一个xtra的文件也不影响最基本功能的实现。

**Comment by seisman** [comment]
现在ustcthesis.cls和ustcxtra也不是完全独立的，比如oldfontcfg这个选项，是在ustcthesis.cls中声明的，但具体的字体处理却是在ustcxtra.cls。这意味着如果某人用了basic选项，不包含ustcxtra，与此同时又用了oldfontcfg选项，则实际上oldfontcfg是没有起到效果的。

**Comment by zepinglee** [comment]
ctex 2.0 有个`<scheme = chinese|plain>` 的选项，不知道这个（或者其代码实现有没有帮助）
