### ISSUE TITLE
Tex Live 2015 兼容性

### ISSUE THREAD

**Issue by zepinglee** [ywgATustcbbs/ustcthesis#25]
我的系统是OS X 10.10 + MacTeX 2015，本来想修改一下macfonts选项的字体的，却发现似乎有些兼容性问题。

第一次make报错是这样：

```
(./chapter/chap-req.tex
附录 A
! Missing number, treated as zero.
<to be read again> 
                   _
l.2 ...术大学研究生学位论文撰写规范}
```

我把main.tex里面的appendix注释掉后再make，报错是这样：

```
! Arithmetic overflow.
\dim_eval:n ...N \__dim_eval:w #1\__dim_eval_end: 

l.15 \end
         {document}
```

这个我也看不懂了

**Comment by seisman** [comment]
CentOS 7.1 + TeXLive 2015，同样的错误。

**Comment by ywgATustcbbs** [comment]
我这里没有装texlive2015，而且这个错误看不懂。texlive2015里边是不是那个用到的宏包有了大改动啊

**Comment by zepinglee** [comment]
我目前只了解到ctex包升到2.0了

**Comment by ywgATustcbbs** [comment]
seisman提到了重构，对现有代码进行一下梳理，我也觉得很有必要重写模板了，希望能够获得你的帮助，大家一起来做这个

**Comment by redsky0802** [comment]
Archlinux + TeXLive2015，同样的错误

**Comment by seisman** [comment]
@redsky0802 试试这个：https://github.com/ustctug/ustcthesis

**Comment by redsky0802** [comment]
@seisman 多谢，这个能用

**Comment by ustcxmwu** [comment]
无论是更新ctex 或者是texlive 2015都会出现这个问题，第一次报错
(./chapter/chap-req.tex
附录 A
! Missing number, treated as zero.
<to be read again> 
之后修改ustcthesis.sty 最后一段，给那个if fi 加上大括号问题解决
\renewenvironment{appendix}
{
  {\if@mainmatter
     \@appendixinbackmatterfalse\OLDappendix
  \else
      \@appendixinbackmattertrue\@mainmattertrue\OLDappendix
  \fi}
    \renewcommand\chaptername{\appendixname~\thechapter}}
  {\if@appendixinbackmatter\@mainmatterfalse\fi
}
出现新的问题是编出来的附录的章节的标题没有“附录A” ，貌似是backmatter搞的鬼，求问各位如何解决？

**Comment by ustcxmwu** [comment]
问题解决了，更新ctex 或者升级到texlive 2015之后更改模板最后一段为：
\renewenvironment{appendix}
{
  {\if@mainmatter
     \@appendixinbackmatterfalse\OLDappendix
  \else
      \@appendixinbackmattertrue\@mainmattertrue\OLDappendix
  \fi}
    %\renewcommand\chaptername{\appendixname~\thechapter}}
  \renewcommand\appendixname{}
  \CTEXsetup[name={附录 \space,}]{chapter}
  \CTEXsetup[number={\Alph{chapter}}]{chapter}
}
  {\if@appendixinbackmatter\@mainmatterfalse\fi
}
问题解决

**Comment by AprilCheny** [comment]
Arithmetic overflow.　这个错误也出现了-_-||

**Comment by zepinglee** [comment]
@ustcxmwu 在 mactex 2015 下，按照你的方法还不行。
我pull了你的repo测试的，也是Arithmetic overflow.
