### ISSUE TITLE
为何默认使用Euler数学字体？

### ISSUE THREAD

**Issue by zepinglee** [ywgATustcbbs/ustcthesis#26]
Euler 跟 Times New Roman 很不搭啊，与Euler能够配合的正文字体恐怕只有Concrete吧（比如Knuth的Concrete Math）？

**Comment by ywgATustcbbs** [comment]
这个并不是大问题，是可以取消的

**Comment by zepinglee** [comment]
我一个月前收到一大堆“数学字体这么丑怎么改啊？”
纯属吐槽。
